name: Build and Deploy

on:
  push:
    branches:
      - master # adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Clojure
        run: |
          sudo apt-get install -y openjdk-11-jre-headless
          curl -O https://download.clojure.org/install/linux-install-1.10.3.855.sh
          chmod +x linux-install-1.10.3.855.sh
          sudo ./linux-install-1.10.3.855.sh
          rm linux-install-1.10.3.855.sh

      - name: Install dependencies
        run: npm install

      - name: Build styles
        run: npm run build-styles

      - name: Build ClojureScript
        run: npx shadow-cljs release app

      - name: Deploy to GitHub Pages
        run: |
          mkdir docs
          mv -v resources/public/* docs/
        if: success()

      - name: Commit and push changes
        run: |
          git config user.email "${{ secrets.USER_MAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git add docs
          git commit -m "Auto-build and deploy to GitHub Pages"
          git push
